# Site wide configuration

title:            Mark Schall
locale:           en_US
url:              http://www.maschall.com

image:
  teaser:
  feature:

# Jekyll configuration

permalink:   date
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Mark Schall
  avatar: bio-photo.png
  bio: "Polyglot developer with 8 years experience with Objective-C, .NET, Java, Swift, and Ruby, currently working at [Detroit Labs](http://www.detroitlabs.com)."
  email: hello@maschall.com
  disqus-shortname: maschall
  twitter: mark_schall
  google:
    plus: #username
    analytics: UA-60451793-1
    verify: gcDln25EK7t-wcn_S9H1xZG6W4MDnWEVfjU1HXqHjMs
    ad-client: 
    ad-slot:  
  github: maschall
  stackoverflow: http://stackoverflow.com/users/123456/maschall
  linkedin: maschall

include: [".htaccess"]
exclude: ["Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "CNAME"]

# Default extensions
post_ext: md
page_ext: md
draft_ext: md

# Found in _templates/
post_layout: post
page_layout: page
draft_layout: draft

# Format titles with titlecase?
titlecase: true

